# typed: false
# frozen_string_literal: true

# Homebrew formula for atl — GENERATED by scripts/gen-homebrew-formula.
# Do not edit by hand; regenerate with `make homebrew` on each release and
# copy this file into the tap repository (Formula/atl.rb).
class Atl < Formula
  desc "Git-style CLI for Confluence & Jira, built for coding agents"
  homepage "https://github.com/isukharev/atl"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/isukharev/atl/releases/download/v0.3.0/atl-darwin-arm64"
      sha256 "9c0b5656097c2088fa17c433c33b14bab305572399141fcb73305b355c6bb41a"
    end
    on_intel do
      url "https://github.com/isukharev/atl/releases/download/v0.3.0/atl-darwin-amd64"
      sha256 "3187d5fa4b6afe16ca3bbadca077ed0a596f31ed3fd9f7256215dc28df46f097"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/isukharev/atl/releases/download/v0.3.0/atl-linux-arm64"
      sha256 "be1522b27b4afd1ae14f2881bba4a0d7bbe9e3d3b6ac1fb2c194f7960d1024e9"
    end
    on_intel do
      url "https://github.com/isukharev/atl/releases/download/v0.3.0/atl-linux-amd64"
      sha256 "a874c0decb838d170f8c9a23e38e2afe427b8dc948380d7426e75880066eb209"
    end
  end

  def install
    bin.install Dir["atl-*"].first => "atl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/atl version")
  end
end
