# typed: false
# frozen_string_literal: true

# Homebrew formula for atl — GENERATED by scripts/gen-homebrew-formula.
# Do not edit by hand; regenerate with `make homebrew` on each release and
# copy this file into the tap repository (Formula/atl.rb).
class Atl < Formula
  desc "Git-style CLI for Confluence & Jira, built for coding agents"
  homepage "https://github.com/isukharev/atl"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/isukharev/atl/releases/download/v0.5.1/atl-darwin-arm64"
      sha256 "f7b3605ac150e5fd7137c549e748ee4ef80d9644aa1df3f7f2739e124e17c85f"
    end
    on_intel do
      url "https://github.com/isukharev/atl/releases/download/v0.5.1/atl-darwin-amd64"
      sha256 "fe4c9f07dc3721d51399479a81278deacc232f5143b5aa51d975509b966010e7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/isukharev/atl/releases/download/v0.5.1/atl-linux-arm64"
      sha256 "38ef13b820ef36954d094e6f64c5a2c1ba43fede5a6862d02b0792ed0d26253d"
    end
    on_intel do
      url "https://github.com/isukharev/atl/releases/download/v0.5.1/atl-linux-amd64"
      sha256 "a359dad1365a8ae6029c35e4be1f35da2d09f961980e4a276d18525a685d26c5"
    end
  end

  def install
    libexec.install Dir["atl-*"].first => "atl"
    (bin/"atl").write_env_script libexec/"atl", ATL_NO_UPDATE: "1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/atl version")
  end
end
