# typed: false
# frozen_string_literal: true

# Homebrew formula for atl — GENERATED by scripts/gen-homebrew-formula.
# Do not edit by hand; regenerate with `make homebrew` on each release and
# copy this file into the tap repository (Formula/atl.rb).
class Atl < Formula
  desc "Git-style CLI for Confluence & Jira, built for coding agents"
  homepage "https://github.com/isukharev/atl"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/isukharev/atl/releases/download/v0.1.0/atl-darwin-arm64"
      sha256 "9846d0ff40f74b255548950f4abb53f83cbd34129087359c623b6e8da50834cf"
    end
    on_intel do
      url "https://github.com/isukharev/atl/releases/download/v0.1.0/atl-darwin-amd64"
      sha256 "3fc8283241b3b4dcb4ac0ed4ca2573365df2eaf434d8521274d9bf6ee7d24361"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/isukharev/atl/releases/download/v0.1.0/atl-linux-arm64"
      sha256 "466f3c4b9358263bb2801ee6d0bd21e4a0ef27756d482511a4e0ab4d0dddda3d"
    end
    on_intel do
      url "https://github.com/isukharev/atl/releases/download/v0.1.0/atl-linux-amd64"
      sha256 "e018a23adcce7bb9ed53f40be93b01371129f0701f969f5429852ecf0e0c430a"
    end
  end

  def install
    bin.install Dir["atl-*"].first => "atl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/atl version")
  end
end
